services:
  - type: web
    name: meezanbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: BOT_TOKEN
        sync: false
